services:
  - type: web
    name: fastapi-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

databases:
  - name: fastapi-db
    plan: free
