"""Remove unique constraint from community name

Revision ID: c72c12a3baf2
Revises: 19aacfd4984a
Create Date: 2025-09-03 21:26:44.119289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72c12a3baf2'
down_revision: Union[str, Sequence[str], None] = '19aacfd4984a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communities_name'), table_name='communities')
    op.create_index(op.f('ix_communities_name'), 'communities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communities_name'), table_name='communities')
    op.create_index(op.f('ix_communities_name'), 'communities', ['name'], unique=True)
    # ### end Alembic commands ###
